// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BoardInfo {
  chip: string;
  revision: [number, number] | null;
  crystal_frequency: number;
  features: Array<string>;
  mac_address: string;
  flash_size: string;
}
