// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Device {
  id: string;
  registered_on: string;
  registered_by: string;
  email: string;
}
