// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Firmware {
  id: number;
  version: string;
  filename: string;
  uploaded: string;
  elf_checksum: string | null;
  bin_checksum: string | null;
}
