// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType";

export interface Url {
  url: string;
  file_name: string;
  version: string;
  checksum: string | null;
  file_type: FileType;
}
